# Generated by Django 3.1.5 on 2021-01-29 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='Xm7IjX', editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Employee name should contain only alphabets.', regex='[a-zA-Z\\s]+$'), django.core.validators.MinLengthValidator(3, message='The employee name must be of more than 3 characters.'), django.core.validators.MaxLengthValidator(50, message='The employee name must be of less than 80 characters.')])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(default=144, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Project name should contain only alphanumeric characters.', regex='^(?=.*[a-zA-Z])(?=.*[0-9])[A-Za-z0-9]+$'), django.core.validators.MinLengthValidator(10, message='The project name must be of more than 10 characters.'), django.core.validators.MaxLengthValidator(80, message='The project name must be of less than 80 characters.')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='The project description must be of more than 50 characters.'), django.core.validators.MaxLengthValidator(300, message='The project description must be of less than 300 characters.')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='project_app.employee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_app.project')),
            ],
        ),
    ]
