# Generated by Django 3.1.5 on 2021-01-29 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Employee name should contain only alphabets.', regex='[a-zA-Z ]*$'), django.core.validators.MinLengthValidator(3, message='The employee name must be of more than 3 characters.'), django.core.validators.MaxLengthValidator(50, message='The employee name must be of less than 80 characters.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='jakCzb', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=264, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
