# Generated by Django 3.1.5 on 2021-01-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210130_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='nYe8N3', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=466, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
