# Generated by Django 3.1.5 on 2021-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20210130_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c5rF2h', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=837, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
