# Generated by Django 3.1.5 on 2021-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20210130_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='hBe4TU', editable=False, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=459, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
