# Generated by Django 3.1.5 on 2021-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20210130_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='Golurw', editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=815, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
