# Generated by Django 3.1.5 on 2021-01-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_auto_20210131_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
