# Generated by Django 3.1.5 on 2021-01-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_auto_20210131_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_employee',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='project_employee',
            old_name='project_id',
            new_name='project',
        ),
    ]
