# Generated by Django 3.1.5 on 2021-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_auto_20210131_1452'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project_employee',
            constraint=models.UniqueConstraint(fields=('project', 'employee'), name='unique assignment'),
        ),
    ]
